### ISSUE TITLE
Jingpeng Wu: did not hide unselected segments in 2D sections

### ISSUE THREAD

**Issue by seung-issues** [seung-lab/neuroglancer#382] opened 2019-11-05 18:46 UTC
| Name | Type | OS | Browser |
|---|---|---|---|
| Jingpeng Wu | Bug | Linux | Chrome |

Description: I selected some segments, but all segments in 2D sections are visible. I think only selected segments should be visible.
![Imgur](https://i.imgur.com/3tyxAkj.png)
<details>
<summary>State URL</summary>

https://neuromancer-seung-import.appspot.com/?json_url=https://www.dynamicannotationframework.com/nglstate/5241263095873536
</details>

**Comment by nkemnitz** [comment] 2019-11-05 19:49
Acknowledged; duplicate of #345. It works correctly when the image layer is the left most layer

**Closed by nkemnitz** 2019-11-05 19:49 UTC
Labels: Realm: Google, Type: Bug
